# Run security audits
name: Security-Audits
on:
  - push
  - pull_request
jobs:
  # Audit all source code with CodeQL (https://semmle.com)
  codeql:
    name: Audit source code with CodeQL
    runs-on: windows-latest
    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Setup CodeQL
      - name: Setup CodeQL
        uses: github/codeql-action/init@v1
        with:
          languages: csharp

      # Setup MSBuild
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1

      # Build the solution
      - name: Build the solution
        run: msbuild ./orange-thallium.sln /property:Configuration=Release /property:Platform=x64

      # Perform CodeQL analysis
      - name: Perform CodeQL analysis
        uses: github/codeql-action/analyze@v1