# Run security audits
name: Security-Audits
on:
  - push
  - pull_request
jobs:
  # Audit all source code with CodeQL (https://semmle.com)
  codeql:
    name: Audit source code with CodeQL
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Setup CodeQL
      - name: Setup CodeQL
        uses: github/codeql-action/init@v1
        with:
          languages: csharp

      # Automatically build
      - name: Automatically build
        uses: github/codeql-action/autobuild@v1

      # Perform CodeQL analysis
      - name: Perform CodeQL analysis
        uses: github/codeql-action/analyze@v1